name: Lint Checks
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    checks:
        name: Run Lint Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly-2026-02-24
                  components: rustfmt, clippy, rust-src
                  target: x86_64-unknown-none, aarch64-unknown-none
            - name: Run cargo fmt
              run: cargo fmt --all -- --check
            - name: Run cargo clippy (x86_64)
              run: cargo clippy --locked --target x86_64-unknown-none -Zbuild-std=core,alloc -Zpanic-abort-tests -- -D warnings
            - name: Run cargo clippy (aarch64)
              run: cargo clippy --locked --target aarch64-unknown-none -Zbuild-std=core,alloc -Zpanic-abort-tests -- -D warnings
            - name: Run cargo clippy (x86_64) (tests)
              run: cargo clippy --locked --tests --target x86_64-unknown-none -Zbuild-std=core,alloc -Zpanic-abort-tests -- -D warnings
            - name: Run cargo clippy (aarch64) (tests)
              run: cargo clippy --locked --tests --target aarch64-unknown-none -Zbuild-std=core,alloc -Zpanic-abort-tests -- -D warnings
